// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Xml.Serialization;

using Newtonsoft.Json;

namespace GoogleMapsGeocoding.Common
{
#if !PORTABLE
    [Serializable]
#endif
    public class Geometry
    {
        [JsonProperty("bounds")]
        [XmlElement("bounds")]
        public Bounds Bounds { get; set; }

        [JsonProperty("location")]
        [XmlElement("location")]
        public Location Location { get; set; }

        [JsonProperty("location_type")]
        [XmlElement("location_type")]
        public string LocationType { get; set; }

        [JsonProperty("viewport")]
        [XmlElement("viewport")]
        public Viewport Viewport { get; set; }
    }
}
