// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Xml.Serialization;

using Newtonsoft.Json;

namespace GoogleMapsGeocoding.Common
{
    [Serializable]
    public class Northeast
    {
        [JsonProperty("lat")]
        [XmlElement("lat")]
        public double Lat { get; set; }

        [JsonProperty("lng")]
        [XmlElement("lng")]
        public double Lng { get; set; }
    }
}
