// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Xml.Serialization;

using Newtonsoft.Json;

namespace GoogleMapsGeocoding.Common
{
#if !PORTABLE
    [Serializable]
#endif
    public class Viewport
    {
        [JsonProperty("northeast")]
        [XmlElement("northeast")]
        public Northeast Northeast { get; set; }

        [JsonProperty("southwest")]
        [XmlElement("southwest")]
        public Southwest Southwest { get; set; }
    }
}
